<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWcie26a\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWcie26a/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerWcie26a.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerWcie26a\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerWcie26a\appProdProjectContainer([
    'container.build_hash' => 'Wcie26a',
    'container.build_id' => 'b9a6e3a0',
    'container.build_time' => 1638015186,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWcie26a');
