<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMomzkxd\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMomzkxd/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMomzkxd.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMomzkxd\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerMomzkxd\appDevDebugProjectContainer([
    'container.build_hash' => 'Momzkxd',
    'container.build_id' => '25259572',
    'container.build_time' => 1642539880,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMomzkxd');
