<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVuhwbhg\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVuhwbhg/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerVuhwbhg.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerVuhwbhg\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerVuhwbhg\appProdProjectContainer([
    'container.build_hash' => 'Vuhwbhg',
    'container.build_id' => 'afe3648a',
    'container.build_time' => 1638015192,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVuhwbhg');
