<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVhfq8zs\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVhfq8zs/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVhfq8zs.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVhfq8zs\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVhfq8zs\appDevDebugProjectContainer([
    'container.build_hash' => 'Vhfq8zs',
    'container.build_id' => 'f220e734',
    'container.build_time' => 1642539882,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVhfq8zs');
